-- L. Glow — AI-generated guidance cache for the practitioner hub. First LLM
-- integration in this app, and the first practitioner-only AI content —
-- generated by supabase/functions/generate-ai-guidance (Edge Function,
-- holds ANTHROPIC_API_KEY server-side, same shape as
-- notify-intake-complete's RESEND_API_KEY pattern). Never shown to the
-- client — practitioner-only, same as practitioner_notes, and for the
-- same reason: this is Thea's own working reference, not authored content
-- being delivered to a user.
--
-- One cached row per (client, assessment, tier) — regenerating overwrites
-- rather than accumulating history, unlike the raw result tables. `tier`
-- defaults to 'none' (not null) so the uniqueness constraint behaves
-- correctly for dosha/guna/agni/tongue, which have no tiers — Postgres
-- treats NULL as distinct from NULL in a unique constraint, which would
-- silently break the one-row-per-assessment invariant if tier were
-- nullable.

create table public.ai_guidance (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references public.users (id) on delete cascade,
  assessment_type text not null check (assessment_type in ('dosha', 'guna', 'agni', 'tongue', 'prakriti', 'vikriti')),
  tier           text not null default 'none',
  content        text not null,
  generated_by   uuid not null references public.users (id),
  generated_at   timestamptz not null default now(),
  unique (user_id, assessment_type, tier)
);

alter table public.ai_guidance enable row level security;

create policy "Practitioners can manage guidance for consented clients"
  on public.ai_guidance for all
  using (
    exists (select 1 from public.users owner where owner.id = ai_guidance.user_id and owner.consented_to_practitioner_view = true)
    and public.is_practitioner()
  )
  with check (
    exists (select 1 from public.users owner where owner.id = ai_guidance.user_id and owner.consented_to_practitioner_view = true)
    and public.is_practitioner()
    and generated_by = auth.uid()
  );
