-- L. Glow — AI-drafted "User's Manual" per client, reviewed by Thea before
-- the client ever sees it. Generated by supabase/functions/generate-user-
-- manual (Edge Function, holds ANTHROPIC_API_KEY server-side, same shape as
-- generate-ai-guidance). Unlike ai_guidance (practitioner-only, never
-- client-visible), this table's whole point is to eventually reach the
-- client — but only once a practitioner has reviewed/edited it and marked
-- it approved.
--
-- One row per client — regenerating overwrites both `ai_draft` and
-- `content` (the practitioner UI must warn before calling generate again if
-- `content` has already diverged from `ai_draft`, since that means Thea's
-- edited it and a blind regenerate would discard that work).

create table public.user_manuals (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.users (id) on delete cascade,
  ai_draft      text not null,   -- original Claude output, preserved even after edits
  content       text not null,   -- editable; starts equal to ai_draft
  status        text not null default 'draft' check (status in ('draft', 'approved')),
  generated_at  timestamptz not null default now(),
  generated_by  uuid not null references public.users (id),
  edited_at     timestamptz,
  approved_at   timestamptz,
  approved_by   uuid references public.users (id),
  unique (user_id)
);

alter table public.user_manuals enable row level security;

create policy "Practitioners can manage manuals for consented clients"
  on public.user_manuals for all
  using (
    exists (select 1 from public.users owner where owner.id = user_manuals.user_id and owner.consented_to_practitioner_view = true)
    and public.is_practitioner()
  )
  with check (
    exists (select 1 from public.users owner where owner.id = user_manuals.user_id and owner.consented_to_practitioner_view = true)
    and public.is_practitioner()
  );

-- The one new RLS shape in this codebase: owner-read gated on an approval
-- status, not unconditional. Every other "Owner full access" policy
-- (checkins, journal_entries, etc.) grants a user full read/write on their
-- own row with no extra condition — a client here only ever gets read
-- access, and only once `status = 'approved'`. No client-write policy
-- exists at all; only a practitioner can create or edit a manual.
create policy "Client can read their own approved manual"
  on public.user_manuals for select
  using (auth.uid() = user_id and status = 'approved');
